spring.datasource.url=jdbc:mysql://localhost:3306/autowash_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=root

spring.datasource.password=admin1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thêm cấu hình khởi tạo DB bằng data.sql sau khi hibernate tạo table
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
spring.sql.init.continue-on-error=true
